apiVersion: v1
kind: ServiceAccount
metadata:
  name: akv-sync-sa
  namespace: akv-sync
  annotations:
    azure.workload.identity/client-id: "${CLIENT_ID}"
    azure.workload.identity/tenant-id: "${TENANT_ID}"
  labels:
    azure.workload.identity/use: "true"
